spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: create
        defer-datasource-initialization: true
    output:
        ansi:
            enabled: always